services:
  fastify-opti-app:
    build: ./fastify
    container_name: fastify-opti-app
    image: fastify-opti-app:latest
    ports:
      - "3015:3015"
    network_mode: "host"
    environment:
      PORT: 3015
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

  express-opti-app:
    build: ./express
    container_name: express-opti-app
    image: express-opti-app:latest
    depends_on: 
      - fastify-opti-app
    ports:
      - "3010:3010"
    network_mode: "host"
    environment:
      PORT: 3010
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb
  
  checkout-worker:
    build: ./express
    container_name: checkout-worker
    image: checkout-worker:latest
    depends_on: 
      - express-opti-app
    network_mode: "host"
    command: node src/workers/checkout.worker.js
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb
  

  # email-worker:
  #   build: ./express
  #   container_name: email-worker
  #   image: email-worker:latest
  #   depends_on:
  #     - express-opti-app
  #   network_mode: "host"
  #   command: node src/workers/email.worker.js

  # stock-worker:
  #   build: ./express
  #   container_name: stock-worker
  #   image: stock-worker:latest
  #   depends_on: 
  #     - express-opti-app
  #   network_mode: "host"
  #   command: node src/workers/stock.worker.js
  #   environment:
  #     DB_HOST: 127.0.0.1
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: psql
  #     DB_NAME: mydb
  
  
  # cart-worker:
  #   build: ./express
  #   container_name: cart-worker
  #   image: cart-worker:latest
  #   depends_on: 
  #     - express-opti-app
  #   network_mode: "host"
  #   command: node src/workers/cart.worker.js
  #   environment:
  #     DB_HOST: 127.0.0.1
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: psql
  #     DB_NAME: mydb